### ISSUE TITLE
When a device is removed from a connected account, it can not be reconnected via another account

### ISSUE THREAD

**Issue by seveibar** [seamapi/public-tracker#10]
### Prerequisites

- Can this issue be reproduced in a sandbox workspace? **No**
- Does this issue represent a regression? Did it previously work? **No**

### Description

If you have a connected account where a device was removed, it cannot be added if you connect a new connected account.

### Steps to Reproduce

1. Connect Account A
2. Remove a device from account A outside of Seam
3. Device will have error `device_removed`
4. Connect Account B that is also connected to the device
5. Connect Account B will have an error `devices_connected_to_other_account`

**Expected behavior:** Adding a new connected account should "take over" a device removed from another account.

### Additional Information

- Slack Conversation: https://hello-seam.slack.com/archives/C041U284Z5K/p1688620459897609?thread_ts=1688393150.304139&cid=C041U284Z5K

**Comment by codetheweb** [comment]
Resolved for Schlage but not August.
