### ISSUE TITLE
Access codes aren't created when IglooHome device is using an accessory keypad

### ISSUE THREAD

**Issue by panzerchris** [seamapi/public-tracker#105]
### Prerequisites

- Can this issue be reproduced in a sandbox workspace? **No**
- Does this issue represent a regression? Did it previously work? **No**

### Description

Access codes cannot be set on IglooHome devices that have an accessory keypad attached (retrofit locks).

### Steps to Reproduce

1. Manage Igloohome device with keypad accessory (no built-in keypad)
2. Create access code on device (offline w/ algopin)

**Expected behavior:** Access code is created on device.

**Actual behavior:** Corresponding Igloo job is never completed.

### Additional Information

https://hello-seam.slack.com/archives/C041U284Z5K/p1710446587567929
https://hello-seam.slack.com/archives/C0586B3NSPL/p1712296316481119

**Comment by codetheweb** [comment]
[Related to a Slack conversation](https://seam.unthread.io/dashboard/inbox/all/conversations/13652460-380d-4076-83be-5c6af32cf2a6)
