### ISSUE TITLE
Online CLI is failing due to a CORS error

### ISSUE THREAD

**Issue by phpnode** [seamapi/public-tracker#116]
We appear to be receiving a CORS error when trying to execute commands via the [online CLI](https://cli.seam.co/).

Details here: https://seam.unthread.io/dashboard/inbox/me/conversations/9eb79708-fdac-49ee-88da-ec778a6da9c8

**Comment by kainpets** [comment]
Couldn't replicate the issue 
<img width="958" alt="Screenshot 2024-05-10 at 19 57 23" src="https://github.com/seamapi/public-tracker/assets/41388251/3cee77e0-e0cd-422c-9b14-a05fb4fb0bcd">
<img width="958" alt="Screenshot 2024-05-10 at 19 57 29" src="https://github.com/seamapi/public-tracker/assets/41388251/ae9966d5-0552-4f89-b347-f5e1d2452089">
