### ISSUE TITLE
Igloohome Not Creating PIN Codes on Lock

### ISSUE THREAD

**Issue by abimaelmartell** [seamapi/public-tracker#132]
### Prerequisites

* Can this issue be reproduced in a sandbox workspace? No
* Does this issue represent a regression? Did it previously work? Yes

### Description

Some IglooHome devices are experiencing problems when trying to create PIN codes. Internally, our system is trying to create the PIN code, but when we send the jobs to the bridge, they expire within minutes, and never get processed.

We confirmed that both the lock, and the bridge are online.

### Additional Information

We reached out to Igloohome and we got a response about a limit of jobs per bridge, but we are waiting on details about how much jobs can a bridge process and whats the timeframe for that limit.

Customer thread: 

[https://hello-seam.slack.com/archives/C041U284Z5K/p1714582534937749](https://hello-seam.slack.com/archives/C041U284Z5K/p1714582534937749)

**Comment by Dyteus** [comment]
Hello, any progress here?

**Comment by panzerchris** [comment]
This has now been resolved.
