### ISSUE TITLE
Set schlage outage error for when we get a 504 error when syncing access codes

### ISSUE THREAD

**Issue by ethanplee14** [seamapi/public-tracker#59]
### Description

Schlage occasionally goes offline and throws 504 of 502 errors. If the access code was previously set and then schlage goes offline it can cause a "modified external to seam" error which is misleading. Update the error map with a descriptive exception

**Comment by mastafit** [comment]
We need to wait for another instance of this happening to capture logs from prod to try and understand the reproduction steps

**Comment by justsayknarf** [comment]
Another instance! https://hello-seam.slack.com/archives/C0625RH4MMM/p1715879579227979?thread_ts=1713891523.151359&cid=C0625RH4MMM
