### ISSUE TITLE
Emit events when converting managed and unmanaged devices

### ISSUE THREAD

**Issue by seveibar** [seamapi/public-tracker#6]
### Prerequisites

- Can this issue be reproduced in a sandbox workspace? **Yes**
- Does this issue represent a regression? Did it previously work? **No**

### Description

`device.connected` should be emitted after managing a device.

### Steps to Reproduce

1. Unmanage a sandbox device ("Deactivate Device" in console)
2. Re-manage the sandbox device
3. Device does not have a new `device.connected` event

**Comment by ethanplee14** [comment]
Do we want to emit `device.connected` or do we want to keep the same behavior of access codes and do `device.unmanaged.converted_to_managed`

**Comment by razor-x** [comment]
I agree we should NOT emit `device.connected` and follow the same conventions as access codes with the `device.unmanaged.converted_to_managed` and `device.converted_to_unmanaged`.

**Comment by razor-x** [comment]
New events documented in this PR: https://github.com/seamapi/api-docs/pull/122 and live at https://docs.seam.co/latest/api-clients/events#event-types

See `device.converted_to_unmanaged` and `device.unmanaged.converted_to_managed`.
