### ISSUE TITLE
Java ConnectedAccount GET not working with personal access token

### ISSUE THREAD

**Issue by peda** [seamapi/public-tracker#62]
### Prerequisites

- Can this issue be reproduced in a sandbox workspace? **Yes**
- Does this issue represent a regression? Did it previously work? **Yes**

### Description

In the latest release of the Java SDK the ConnectedAccount get() request is not working, when using personal access tokens. Server returns an error with status code `400`

In addition, the ConnectedAccount get() method design differentiates from the services - it's the only one I encountered so far which isn't using the builder pattern.

### Steps to Reproduce

```
seam.connectedAccounts().get(ConnectedAccountsGetRequest.id(connectedAccountId))
```

**Expected behavior:** get the ConnectedAccount returned instead of an error

**Actual behavior:** exception gets thrown and request failed

### Versions

- [ ] I am using the JAVA SDK version 0.1.26

### Additional Information

I've been using a personal access token, instead of a workspace API key.

**Comment by seveibar** [comment]
Thanks @peda! Having a team look into this

**Comment by dsinghvi** [comment]
@peda what version of the java SDK did this used to work on?

**Comment by peda** [comment]
@dsinghvi I only started using Seam recently, so I unfortunately can't tell if it did work on a previous version. I did some more tests yesterday and on the latest version (0.1.26) it is working with API keys only, but not with personal access tokens.

**Comment by dsinghvi** [comment]
@peda I just released a new version of the java sdk (0.2.0) and some instructions around how to use it with PATs (https://github.com/seamapi/java#using-pats). Let me know if that works for you!

**Comment by peda** [comment]
@dsinghvi sorry, the time around the end of the year was very busy for us - I'll give it a try in the next few days and let you know

**Comment by peda** [comment]
@dsinghvi thanks - everything is working as expected
