### ISSUE TITLE
Add support for unlock events

### ISSUE THREAD

**Issue by sybohy** [seamapi/public-tracker#74]
### Description

Igloo devices can be unlocked via an API call, BLE key, or a PIN code. The Seam API does not currently support real-time event/notification for those events. We wish to add this support to provide greater insight. 

### Steps to Reproduce

1. Pair a real Igloo lock device
2. Program an access code
3. Unlock the device using the access code
4. No event is sent to Seam

**Expected behavior:** an unlock event, including the access code that was used, should be emitted. 

**Actual behavior:** No events are currently available

### Versions

- [ ] I am using the [language] SDK version [version of sdk you're using]

### Additional Information

Internal [Seam support ticket](https://app.intercom.com/a/inbox/u5k9m719/inbox/search/conversation/3060)

**Comment by phpnode** [comment]
https://hello-seam.slack.com/archives/C041U284Z5K/p1712573681026869
