### ISSUE TITLE
Seam sometimes returns a negative battery level

### ISSUE THREAD

**Issue by seveibar** [seamapi/public-tracker#9]
### Prerequisites

- Can this issue be reproduced in a sandbox workspace? **No**
- Does this issue represent a regression? Did it previously work? **Maybe**

### Description

Sometimes Seam will return a negative battery level, the battery level will eventually correct itself.

### Steps to Reproduce

Can be reproduced on some August devices, presumably when August returns a negative battery level

**Comment by itelo** [comment]
If the provider returns a negative number, we could either:
* ignore the new value (that is probably incorrect anyway) and use the old one.
 
or 

* update the value to something like "unknown."

**Comment by seveibar** [comment]
@itelo for the purpose of computing the average battery level, we want to ignore storing the negative value in the capability state for the device.

For displaying the unknown battery level for the customer, instead of returning "unknown" we'll want to leave the battery level undefined, I believe there's something like `device.properties.battery.status` which can be set to `"unknown"`

**Comment by itelo** [comment]
I believe the `"unknown"` comes from the frontend.
